// <auto-generated />
using System;
using EmployeeManagementSystem.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeManagementSystem.Migrations
{
    [DbContext(typeof(EmployeeManagementSystemContext))]
    [Migration("20250328043853_AddPrimaryKeysV5")]
    partial class AddPrimaryKeysV5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementSystem.DataModel.EmployeeModel", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employee_id"));

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("hire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("kana_first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kana_last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("office_id")
                        .HasColumnType("integer");

                    b.Property<string>("phone_num")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("position_id")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("employee_id");

                    b.ToTable("employee", "public");
                });

            modelBuilder.Entity("EmployeeManagementSystem.DataModel.OfficeModel", b =>
                {
                    b.Property<int>("office_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("office_id"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("office_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("office_id");

                    b.ToTable("office", "public");
                });

            modelBuilder.Entity("EmployeeManagementSystem.DataModel.OperatorModel", b =>
                {
                    b.Property<int>("operator_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("operator_id"));

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("position_id")
                        .HasColumnType("integer");

                    b.HasKey("operator_id");

                    b.HasIndex("employee_id");

                    b.ToTable("operator", "public");
                });

            modelBuilder.Entity("EmployeeManagementSystem.DataModel.PositionModel", b =>
                {
                    b.Property<int>("position_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("position_id"));

                    b.Property<string>("position_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("position_id");

                    b.ToTable("position", "public");
                });

            modelBuilder.Entity("EmployeeManagementSystem.DataModel.OperatorModel", b =>
                {
                    b.HasOne("EmployeeManagementSystem.DataModel.EmployeeModel", "EmployeeIdNavigation")
                        .WithMany("Operators")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeIdNavigation");
                });

            modelBuilder.Entity("EmployeeManagementSystem.DataModel.EmployeeModel", b =>
                {
                    b.Navigation("Operators");
                });
#pragma warning restore 612, 618
        }
    }
}
